version: "3.1"
services:

  # PHP 82 Application
  php82_web:
    container_name: php82_web
    build: ./build/php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8200:80"
    networks:
      -  network_php82_web
 

  # MySQL database for PHP 82
  mysql_php82_web:
    # image: mysql:latest
    container_name: mysql_php82_web
    build: ./build/mysql
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123
      MYSQL_USER: droot
      MYSQL_PASSWORD: Pass123
      MYSQL_DATABASE: php82_test_db
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    networks:
      -  network_php82_web

# phpmyadmin for PHP 82
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php82_web_phpmyadmin
    depends_on:
      - mysql_php82_web
    ports:
      - "8201:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_php82_web
      PMA_PORT: 3306
      MYSQL_USER: droot
      MYSQL_PASSWORD: Pass123
      MYSQL_ROOT_PASSWORD: RootPass123
      UPLOAD_LIMIT: 64M
    restart: always
    networks:
      -  network_php82_web
volumes:
  cakedb_data:

# Newwork  
networks:
  network_php82_web:
    driver: bridge